services:
    php:
        build: 
            context: ./.docker/php
            args:
                SERVER_NAME: ${SERVER_NAME}
        container_name: php
        volumes:
            - ./php/vhosts:/etc/apache2/sites-enabled
            - ./app:/var/www/app
        restart: unless-stopped
        networks:
            - rm-web_network

networks:
    rm-web_network:
