app:
    resource: '../src/Controller/Portfolio/**/*'
    type: attribute
    name_prefix: app_
    prefix: /{_locale}
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locales: '%locale%'
    options:
        expose: true

seo:
    resource: '../src/Controller/SEO/**/*'
    type: attribute
    name_prefix: app_seo_
    options:
        expose: true

redirect:
    path: /
    controller: App\Controller\RedirectController::redirectToLocale
